dataframe_rows: 20
length_strings: 30
length_bytes: 15
max_integer: 1000
hex_number_length: 15
rubbish_to_insert:
    .NAN: 0.025
    null: 0.025
    'NULL': 0.025
    'NONE': 0.025
    'NaN': 0.025
    ' ': 0.025
datetime_start: 2020-01-01
datetime_end: 2030-12-31
example_columns:
    'CACONT_ACC': 'ACCOUNT'
    'PROFORMA_GUID': 'BYTE'
    'CALL_ATTEMPTS': 'INTEGER'
    'BALANCE': 'FLOAT'
    'CALL_DATE': 'DATETIME'
    'EXHAUSTED_REASON': 'STRING'
    'GUID_HEX': 'HEX'